# Generated by Django 4.1.6 on 2023-09-17 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_books', models.IntegerField()),
                ('revenue', models.FloatField()),
                ('available_books', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoldBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('book_cover', models.ImageField(default='default-cover', upload_to='cover_images/')),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                # ('stock_quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sold_date', models.DateField(auto_now_add=True)),
                ('sold_time', models.TimeField(auto_now_add=True)),
                ('is_return', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sold_date', '-sold_time'],
            },
        ),
        migrations.CreateModel(
            name='BooksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('book_cover', models.ImageField(default='default-cover', upload_to='cover_images/')),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=10)),
                ('pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=50)),
                ('year_published', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
