# Generated by Django 4.1.6 on 2023-09-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_soldbooks_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='available_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='revenue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='sold_books',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statusreport',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
